# Generated by Django 4.2.16 on 2024-10-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('is_confirmed', models.BooleanField(default=False)),
                ('confirmation_token', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
